### ISSUE TITLE
[Anon] Bug report: Warriors_of_Chaos.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-armies-project#11]
**File:** Warriors_of_Chaos.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Marks of chaos missing for heroes and lords.
Several mounts missing for Lords and heroes. Disc of tzeench among them.

**Comment by L3610N115** [comment]
On mobile click the circle to select the marks.
When you have the specific mark you also gain access to the mark specific mounts.
