### ISSUE TITLE
[Anon] Bug report: Ogre_Kingdoms.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-armies-project#20]
**File:** Ogre_Kingdoms.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Jhared the Red - as a hunter he cannot become a "general" but the options of BattleScribe make it possible to mark him as a "general"
The non named hero "hunter" do not have this marking option as it should be.

**Comment by L3610N115** [comment]
fixed
