### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by JuliusCaesar007** [BSData/warhammer-armies-project#21]
**Describe the bug**
the ability to choose medium armor for men-at-arms is missing.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by L3610N115** [comment]
They have their own selection entry
