### ISSUE TITLE
Bug Report: Dwarfs.catz

### ISSUE THREAD

**Issue by Martin-Eth** [BSData/warhammer-armies-project#22]
When adding Bugman's Brewers to the Dwarfs roster. the Ol' Deadeye is only showing 1 attack, and there is no option for the unit to take shields.
My understanding from the rule book (page 198), is that you can upgrade a regular unit of rangers to a unit of bugmans rangers. Page 222 shows Rangers can take shields.

**To Reproduce**
1. Go to Dwarves v23
2. Add the Special Character Hero Josef Bugman
3. Click on Ol' Deadeye to add.
4. Click on the Ranger entry to display options.
5. there is no option to take shields (as there is for a regular unit of Rangers)
6. right click on Ol'Dead eye to view the selection, you can see he only has 1 attack.

**Expected behavior**
The options for Bugmans Rangers should be the same as for a normal unit of Rangers
The Attack stat for Bugman's Ol' Deadeye should show 2 when viewing the selection

**Screenshots**
If only i knew how to add them in

**Device and data (please complete the following information):**
 - WIndows 10
 - BattleScribe v2.03.21.166
 - Dwarfs v23 by L3610N 115

Thanks for all the exceptional work on this project.

**Comment by L3610N115** [comment]
Appreciated and fixed!
