### ISSUE TITLE
[Anon] Bug report: Chaos_Dwarfs.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-armies-project#25]
**File:** Chaos_Dwarfs.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Infernal guard are core only if drazoath is taken.  Currently they are always in core no matter what when they should be in special.  The app warns you about not being able to take them but they aren't listed in special.

**Comment by L3610N115** [comment]
That's because the data has not been updated at the time of me posting this.
