### ISSUE TITLE
Lokhir Fellheart. Helm of the Kraken

### ISSUE THREAD

**Issue by xfishburgx** [BSData/warhammer-armies-project#27]
Lokhir Fellheart. Helm of the Kraken's ability is wrong.

It gives 4+ regen and terror

It must give 6+ save; +1 Toughness; and Terror.

**Screenshots**
<img width="621" alt="helm kraken" src="https://user-images.githubusercontent.com/131341365/233360928-02010984-848d-42a9-a22c-86b27dd663b5.PNG">

**Comment by L3610N115** [comment]
That's because the data has not been updated at the time of me posting this.
