### ISSUE TITLE
[Anon] Bug report: Beastmen.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-armies-project#28]
**File:** Beastmen.catz

**BattleScribe version:** 1.16.08

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** 1.16.8 
Great Bray Shaman has no option to upgrade to level 4 and no mark of chaos options allowing access to the chaos lores of magic

**Comment by L3610N115** [comment]
Click the circle to select the variant.
